name: Generate Stats Images

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats
        run: |
          curl -L -A "Mozilla/5.0" -o stats.svg "https://github-readme-stats-lkkivl9st.vercel.app/api?username=Trindadefelipe&show_icons=true&theme=radical&include_all_commits=true&count_private=true"
          curl -L -A "Mozilla/5.0" -o top-langs.svg "https://github-readme-stats-lkkivl9st.vercel.app/api/top-langs/?username=Trindadefelipe&layout=compact&theme=radical"
          head -c 100 stats.svg

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stats.svg top-langs.svg
          git diff --staged --quiet || git commit -m "Update stats"
          git push
